version: "3.2"
services:
  db:
    image: "postgres"
    container_name: "db"
    restart: "always" 
    ports:
      - "1234:5432"
    env_file:
      - ".env"
    volumes:
      - "./pg:/var/lib/postgresql/data"


  node_app:
    container_name: ci_cd
    build: . 
    ports:
      - 5000:5000
    depends_on:
      - db 
    env_file:
      - .env.test 

volumes:
  pg: